In [5]:
import numpy as np

def my_func1(x):
    return x**2
f = lambda x : x**2

def numerical_derivative(f,x):
    delta_x = 1e-4
    return ((f(x+delta_x)-f(x-delta_x))/(2*delta_x))
result = numerical_derivative(f,3)
print("result ==", result)

result = numerical_derivative(my_func1,3)
print("result ==", result)

result == 6.000000000012662
result == 6.000000000012662


In [1]:
import numpy as np
def my_func2(x):
    return 3*x*(np.exp(x))
f = lambda x : my_func2(x)

def numerical_derivative(f,x):
    delta_x = 1e-4
    return ((f(x+delta_x)-f(x-delta_x))/(2*delta_x))

result = numerical_derivative(f,2)
print("result ==", result)

result = numerical_derivative(my_func2,2)
print("result ==", result)



result == 66.50150507518049
result == 66.50150507518049


In [3]:
import numpy as np

#f는 위에 정의된 람다 함수 이고 x는 행렬 값이다.
# ex) f(x,y,z,w) 일때 안에있는 변수들을 행렬로 생각 한다.
def numerical_derivative(f,x):
    delta_x = 1e-4
    #각 변수에 대해서 미분값, zeros_like 는 0행렬된 초기화값이다.
    #grad = ([0,0],[0,0])
    grad = np.zeros_like(x)
    #it는 크기가 얼마가 되던지 제일 처음을 가리킨다.
    it = np.nditer(x,flags=['multi_index'],op_flags = ['readwrite'])
    #it가 끝나기 전까지
    while not it.finished:
        #it의 인덱스를 가져온다.
        idx = it.multi_index
        
        tmp_val = x[idx] #원본값을 저장한다.
        x[idx] = float(tmp_val) + delta_x  #원본값을 저장하는 이유,typecast를 명시적으로 해도 되고 안해도 된다.
        fx1 = f(x) #f(x+delta_x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) #f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val 
        it.iternext()
        
    return grad
        

In [6]:
import numpy as np

def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. initial input variable =",x)
    print("debug 2. initial grad =",grad)
    print("==============================")
    it = np.nditer(x,flags=['multi_index'],op_flags = ['readwrite'])
   
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ",x[idx])
        
        tmp_val = x[idx] 
        x[idx] = float(tmp_val) + delta_x  
        fx1 = f(x) #f(x+delta_x)
        
        print(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) #f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        print(x)
        print("debug 4. grad[idx] = ", grad[idx])
        print("debug 5. grad = ", grad)
        print("============================")
        x[idx] = tmp_val 
        print(x)
        it.iternext()
        
    return grad
def func1(input_obj):
    x = input_obj[0]
    return x**2
f = lambda x : func1(x)
# x =3.0 에서의 편미분 값
numerical_derivative(f,np.array([3.0]))

debug 1. initial input variable = [3.]
debug 2. initial grad = [0.]
debug 3. idx =  (0,) , x[idx] =  3.0
[3.0001]
[2.9999]
debug 4. grad[idx] =  6.000000000012662
debug 5. grad =  [6.]
[3.]


array([6.])

In [8]:
import numpy as np

def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. initial input variable =",x)
    print("debug 2. initial grad =",grad)
    print("==============================")
    it = np.nditer(x,flags=['multi_index'],op_flags = ['readwrite'])
   
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ",x[idx])
        
        tmp_val = x[idx] 
        x[idx] = float(tmp_val) + delta_x  
        fx1 = f(x) #f(x+delta_x)
        
        print(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) #f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        print(x)
        print("debug 4. grad[idx] = ", grad[idx])
        print("debug 5. grad = ", grad)
        print("============================")
        x[idx] = tmp_val 
        print(x)
        it.iternext()
        
    return grad
def func1(W):
    x = W[0]
    y = W[1]
    return (2*x + 3*x*y + np.power(y,3))
f = lambda W : func1(W)
# (x,y) = (1.0, 2.0) 에서의 편미분 값
W = np.array([1.0, 2.0])

numerical_derivative(f,W)

debug 1. initial input variable = [1. 2.]
debug 2. initial grad = [0. 0.]
debug 3. idx =  (0,) , x[idx] =  1.0
[1.0001 2.    ]
[0.9999 2.    ]
debug 4. grad[idx] =  7.999999999990237
debug 5. grad =  [8. 0.]
[1. 2.]
debug 3. idx =  (1,) , x[idx] =  2.0
[1.     2.0001]
[1.     1.9999]
debug 4. grad[idx] =  15.000000010019221
debug 5. grad =  [ 8.         15.00000001]
[1. 2.]


array([ 8.        , 15.00000001])

In [9]:
import numpy as np

def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. initial input variable =",x)
    print("debug 2. initial grad =",grad)
    print("==============================")
    it = np.nditer(x,flags=['multi_index'],op_flags = ['readwrite'])
   
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ",x[idx])
        
        tmp_val = x[idx] 
        x[idx] = float(tmp_val) + delta_x  
        fx1 = f(x) #f(x+delta_x)
        
        print(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) #f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        print(x)
        print("debug 4. grad[idx] = ", grad[idx])
        print("debug 5. grad = ", grad)
        print("============================")
        x[idx] = tmp_val 
        print(x)
        it.iternext()
        
    return grad
def func1(input_obj):
    w = input_obj[0,0]
    x = input_obj[0,1]
    y = input_obj[1,0]
    z = input_obj[1,1]
    
    return (w*x + x*y*z + 3*w + z*np.power(y,2))
input = np.array([[1.0,2.0],[3.0,4.0]])
numerical_derivative(func1,input)

debug 1. initial input variable = [[1. 2.]
 [3. 4.]]
debug 2. initial grad = [[0. 0.]
 [0. 0.]]
debug 3. idx =  (0, 0) , x[idx] =  1.0
[[1.0001 2.    ]
 [3.     4.    ]]
[[0.9999 2.    ]
 [3.     4.    ]]
debug 4. grad[idx] =  5.000000000023874
debug 5. grad =  [[5. 0.]
 [0. 0.]]
[[1. 2.]
 [3. 4.]]
debug 3. idx =  (0, 1) , x[idx] =  2.0
[[1.     2.0001]
 [3.     4.    ]]
[[1.     1.9999]
 [3.     4.    ]]
debug 4. grad[idx] =  13.00000000000523
debug 5. grad =  [[ 5. 13.]
 [ 0.  0.]]
[[1. 2.]
 [3. 4.]]
debug 3. idx =  (1, 0) , x[idx] =  3.0
[[1.     2.    ]
 [3.0001 4.    ]]
[[1.     2.    ]
 [2.9999 4.    ]]
debug 4. grad[idx] =  32.00000000006753
debug 5. grad =  [[ 5. 13.]
 [32.  0.]]
[[1. 2.]
 [3. 4.]]
debug 3. idx =  (1, 1) , x[idx] =  4.0
[[1.     2.    ]
 [3.     4.0001]]
[[1.     2.    ]
 [3.     3.9999]]
debug 4. grad[idx] =  15.000000000000568
debug 5. grad =  [[ 5. 13.]
 [32. 15.]]
[[1. 2.]
 [3. 4.]]


array([[ 5., 13.],
       [32., 15.]])

In [11]:
import numpy as np

def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    print("debug 1. initial input variable =",x)
    print("debug 2. initial grad =",grad)
    print("==============================")
    it = np.nditer(x,flags=['multi_index'],op_flags = ['readwrite'])
   
    while not it.finished:
        idx = it.multi_index
        
        print("debug 3. idx = ", idx, ", x[idx] = ",x[idx])
        
        tmp_val = x[idx] 
        x[idx] = float(tmp_val) + delta_x  
        fx1 = f(x) #f(x+delta_x)
        
        print(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) #f(x-delta_x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        print(x)
        print("debug 4. grad[idx] = ", grad[idx])
        print("debug 5. grad = ", grad)
        print("============================")
        x[idx] = tmp_val 
        print(x)
        it.iternext()
        
    return grad
#행렬을 벡터로 변환 *항상 데이터의 입력을 주는 부분을 바꾸어주어야한다.*
def func1(input_obj):
    w = input_obj[0]
    x = input_obj[1]
    y = input_obj[2]
    z = input_obj[3]
    #w = input_obj[0,0]
    #x = input_obj[0,1]
    #y = input_obj[1,0]
    #z = input_obj[1,1]
    return (w*x + x*y*z + 3*w + z*np.power(y,2))
input = np.array([1.0,2.0,3.0,4.0])
#input = np.array([1.0,2.0,3.0,4.0]).reshape(2,2)
numerical_derivative(func1,input)

debug 1. initial input variable = [1. 2. 3. 4.]
debug 2. initial grad = [0. 0. 0. 0.]
debug 3. idx =  (0,) , x[idx] =  1.0
[1.0001 2.     3.     4.    ]
[0.9999 2.     3.     4.    ]
debug 4. grad[idx] =  5.000000000023874
debug 5. grad =  [5. 0. 0. 0.]
[1. 2. 3. 4.]
debug 3. idx =  (1,) , x[idx] =  2.0
[1.     2.0001 3.     4.    ]
[1.     1.9999 3.     4.    ]
debug 4. grad[idx] =  13.00000000000523
debug 5. grad =  [ 5. 13.  0.  0.]
[1. 2. 3. 4.]
debug 3. idx =  (2,) , x[idx] =  3.0
[1.     2.     3.0001 4.    ]
[1.     2.     2.9999 4.    ]
debug 4. grad[idx] =  32.00000000006753
debug 5. grad =  [ 5. 13. 32.  0.]
[1. 2. 3. 4.]
debug 3. idx =  (3,) , x[idx] =  4.0
[1.     2.     3.     4.0001]
[1.     2.     3.     3.9999]
debug 4. grad[idx] =  15.000000000000568
debug 5. grad =  [ 5. 13. 32. 15.]
[1. 2. 3. 4.]


array([ 5., 13., 32., 15.])