In [24]:
import numpy as np
from datetime import datetime

##################### 미분함수 ####################
def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    it = np.nditer(x,flags=['multi_index'],op_flags = ['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        x[idx] = tmp_val
        it.iternext()
    return grad
##########################################################
#####################입력부분#############################
#load_data = np.loadtxt('./regression_testdata_03.csv',delimiter=',', dtype = np.float32)
x_data = np.array([1,2,3,4,5])
t_data = np.array([2,3,4,5,6])
print(x_data.ndim,t_data.ndim)
W = np.random.rand(1,1)
b = np.random.raload_data = np.loadtxt('./regression_testdata_03.csv',delimiter=',', dtype = np.float32)
x_data = load_data[:,0:-1]
t_data = load_data[:,[-1]]nd(1)
print("W =", W,", W.shape =", W.shape, ",b= ", b,",b.shape =", b.shape)
###########################################################
def loss_func(x,t):
    y = np.dot(x,W) + b
    return np.sum((t-y)**2) / len(x)

def error_val(x,t):
    y = np.dot(x,W) + b
    return np.sum((t-y)**2) / len(x)

def predict(x):
    y = np.dot(x,W) + b
    return y

learning_rate = 1e-2
f = lambda x : loss_func(x_data,t_data)
print("initial error value =", error_val(x_data.reshape(5,1),t_data.reshape(5,1)),"Initial W = ", W, "\n",", b = ", b)
start_time = datetime.now()
for step in range(8001):
    for index in range(len(x_data)): # 행렬로 하지 않고 벡터로 하는경우 시간이 10배정도 더 걸린다.
        input_x_data = x_data[index]
        input_t_data = t_data[index]
        
        f = lambda x : loss_func(np.array([input_x_data]), np.array([input_t_data]))  
        W -= learning_rate * numerical_derivative(f,W)
        b -= learning_rate * numerical_derivative(f,b)

        if(step % 400 == 0):
            print("step =", step, "error value = ", error_val(x_data.reshape(5,1),t_data.reshape(5,1)), "W = ", W,", b = ",b)

end_time = datetime.now()
print("")
print("Time : ",end_time - start_time)
test_score = np.array([30])
predict(test_score)


1 1
W = [[0.55032737]] , W.shape = (1, 1) ,b=  [0.52970604] ,b.shape = (1,)
initial error value = 3.714306563586078 Initial W =  [[0.55032737]] 
 , b =  [0.52970604]
step = 0 error value =  3.42079745280913 W =  [[0.5687267]] , b =  [0.54773739]
step = 0 error value =  2.7332477092241283 W =  [[0.62131907]] , b =  [0.57192988]
step = 0 error value =  1.7421117434121094 W =  [[0.71516584]] , b =  [0.59758133]
step = 0 error value =  0.8019986737314341 W =  [[0.83850627]] , b =  [0.6185492]
step = 0 error value =  0.2510037208675784 W =  [[0.95739821]] , b =  [0.63043839]
step = 400 error value =  1.1845628103424737e-09 W =  [[1.0000205]] , b =  [0.99991995]
step = 400 error value =  1.1462718305638221e-09 W =  [[1.00002206]] , b =  [0.99992067]
step = 400 error value =  1.1559230467261817e-09 W =  [[1.00002285]] , b =  [0.99992088]
step = 400 error value =  1.143533161712595e-09 W =  [[1.00002187]] , b =  [0.99992072]
step = 400 error value =  1.2404076557244622e-09 W =  [[1.00001886]] 

array([31.])

In [18]:
x_data = np.array([1,2,3,4,5])
t_data = np.array([2,3,4,5,6])
print(x_data)
x = x_data.T
print(x)

[1 2 3 4 5]
[1 2 3 4 5]


In [41]:
def numerical_derivative(f,x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    it = np.nditer(x,flags=['multi_index'],op_flags = ['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        x[idx] = tmp_val
        it.iternext()
    return grad

In [42]:
load_data = np.loadtxt('./data-01.csv',delimiter=',', dtype = np.float32)
x_data = load_data[:,0:-1]
t_data = load_data[:,[-1]]

#데이터 차원 및 shape 확인
print("x_data.ndim = ", x_data.ndim,", x_data.shape = ", x_data.shape)
print("t_data.ndim = ", t_data.ndim,", t_data.shape = ", t_data.shape)


x_data.ndim =  2 , x_data.shape =  (25, 3)
t_data.ndim =  2 , t_data.shape =  (25, 1)


In [47]:
class LinearRegressionTest:
    def __init__(self,x_data,t_data,learning_rate,iteration_count):
        
        self.x_data = x_data
        self.t_data = t_data
        
        self.learning_rate = learning_rate
        self.iteration_count = iteration_count
        
        self.W = np.random.rand(self.x_data.shape[1],1)
        self.b = np.random.rand(1)
        
        print("W =", W,", W.shape =", W.shape, ",b= ", b,",b.shape =", b.shape)
        
    def loss_func(self,x,t):
        self.x = x
        self.t = t
        y = np.dot(self.x,self.W) + self.b
        return np.sum((self.t-y)**2) / len(self.x)
    def error_val(self,x,t):
        self.x = x
        self.t = t
        y = np.dot(self.x,self.W) + self.b
        return np.sum((self.t-y)**2) / len(self.x)
    def predict(self,x):
        self.x = x
        y = np.dot(self.x,self.W) + self.b
        return y
    def train(self):
        f = lambda x : self.loss_func(self.x_data,self.t_data)
        print("initial error value =", self.error_val(self.x_data,self.t_data),
              "Initial W = ", self.W, "\n",", b = ", self.b)
        start_time = datetime.now()
        for step in range(self.iteration_count):
            self.W -= self.learning_rate * numerical_derivative(f,self.W)
            self.b -= self.learning_rate * numerical_derivative(f,self.b)
            
            if(step % 400 == 0):
                print("step =", step, "error value = ", self.error_val(self.x_data,self.t_data), 
                      "W = ", self.W,", b = ",self.b)
        end_time = datetime.now()
        print("")
        print("Elapsed Time -> ", end_time - start_time)

In [48]:
obj = LinearRegressionTest(x_data,t_data,1e-5,10001)
obj.train()

W = [[1.]] , W.shape = (1, 1) ,b=  [1.] ,b.shape = (1,)
initial error value = 516.820378696706 Initial W =  [[0.42688351]
 [0.89041852]
 [0.97045017]] 
 , b =  [0.82415559]
step = 0 error value =  196.87113312941875 W =  [[0.39088253]
 [0.8541008 ]
 [0.93351584]] , b =  [0.82388306]
step = 400 error value =  8.30465940506093 W =  [[0.33599924]
 [0.75525938]
 [0.91680929]] , b =  [0.8229257]
step = 800 error value =  7.692230427033892 W =  [[0.33704579]
 [0.71941196]
 [0.95082956]] , b =  [0.82234567]
step = 1200 error value =  7.262639814641164 W =  [[0.33813214]
 [0.68929404]
 [0.97921268]] , b =  [0.82172938]
step = 1600 error value =  6.961238134585312 W =  [[0.33923179]
 [0.66398273]
 [1.00288617]] , b =  [0.82108288]
step = 2000 error value =  6.749719402597673 W =  [[0.34032448]
 [0.64270447]
 [1.0226256 ]] , b =  [0.8204112]
step = 2400 error value =  6.601231779145674 W =  [[0.34139497]
 [0.62481085]
 [1.03907937]] , b =  [0.81971858]
step = 2800 error value =  6.49695124543382

In [49]:
test_data = np.array([100,98,81])
obj.predict(test_data)

array([178.86928055])