In [14]:
def calc(list_data):
    
    sum = 0
    
    try:
        sum = list_data[0] + list_data[1] + list_data[2]
        
        if sum < 0:
            raise Exception("sum is minus")
    except IndexError as err:
        print(str(err))
    except Exception as err:
        print(str(err))
    finally:
        print(sum)
calc([1,2])

list index out of range
0


#with 구문
일반적으로 파일(file) 또는 세션(session) 을 사용하는 순서는 다음과 같음
open() => read() 또는 write() => close()


In [15]:
f = open("./file_test.txt", 'w')
f.write("Hello, python !!!")
f.close()

In [16]:
with open("./file_test.txt", 'w') as f:
    f.write("hello,python !!!!")

In [24]:
class point:
    def __init__(self,X,Y):
        self.X = X
        self.Y = Y
    def setx(self,X):
        self.X = X
    def sety(self,Y):
        self.Y = Y
    def get(self):
        return self.X, self.Y
    def move(self,dx,dy):
        self.X = self.X + dx
        self.Y = self.Y + dy
obj = point(10,10)
print(obj.get())
obj.setx(15)
obj.sety(20)
print(obj.get())
obj.move(2,5)
print(obj.get())
    


(10, 10)
(15, 20)
(17, 25)


In [53]:
class MyCalc:
    def __init__(self,A,B):
        self.A = A
        self.B = B
        result = 0
    def sum(self):
        result = self.A + self.B
        return result
    def subtract(self):
        result = self.A - self.B
        return result
    def multiply(self):
        result = self.A * self.B
        return result
    def divide(self):
        if self.B == 0:
            raise Exception
        else:
            result = self.A / self.B
            return result
obj2 = MyCalc(20,0)

print(obj2.sum())
print(obj2.subtract())
print(obj2.multiply())
try:
    print(obj2.divide())
except Exception as err:
    print(str(err))

20
20
0



In [65]:
import numpy as np
A = np.array([[1,0],[0,1]])
B = np.array([[1,1],[1,1]])
C = np.array([[1,2,3],[0,1,2],[0,0,1]])
print("A+B =\n",A+B)
print("C=\n",C)
print(C.shape)

A+B =
 [[2 1]
 [1 2]]
C=
 [[1 2 3]
 [0 1 2]
 [0 0 1]]
(3, 3)


In [67]:
A = np.array([1,2,3])
B = np.array([4,5,6])
print("A ==", A, ", B == ",B)
print("A.shape ==",A.shape,",B.shape ==", B.shape)
print("A.ndim ==", A.ndim, "B.ndim ==", B.ndim)

A == [1 2 3] , B ==  [4 5 6]
A.shape == (3,) ,B.shape == (3,)
A.ndim == 1 B.ndim == 1


In [69]:
print("A + B ==", A+B)
print("A - B ==", A-B)
print("A * B ==", A*B)
print("A / B ==", A/B)

A + B == [5 7 9]
A - B == [-3 -3 -3]
A * B == [ 4 10 18]
A / B == [0.25 0.4  0.5 ]


In [71]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[-1,-2,-3],[-4,-5,-6]])
print("A.shape ==",A.shape, "B.shape ==",B.shape)
print("A.ndim ==",A.ndim,"B.ndim ==",B.ndim)
A = A.reshape(3,2)
print(A.shape)

A.shape == (2, 3) B.shape == (2, 3)
A.ndim == 2 B.ndim == 2
(3, 2)


In [72]:
A = np.array([[1,2,3],[4,5,6]]) #2*3 행렬
B = np.array([[-1,-2],[-3,-4],[-5,-6]]) #3*2 행렬
#(2*3)dot product(3*2) == (2*2) 행렬
C = np.dot(A,B) # 행렬곱 수행
print(C)

[[-22 -28]
 [-49 -64]]


In [73]:
A = np.array([[1,2],[3,4]])
B = 5
print(A+B)

[[6 7]
 [8 9]]


In [74]:
A = np.array([[1,2],[3,4],[5,6]]) #3X2 행렬
B = A.T #A의 전치행렬, 2X3 행렬
print("A.shape ==",A.shape,",B.shape ==",B.shape)
print(A)
print(B)

A.shape == (3, 2) ,B.shape == (2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[1 3 5]
 [2 4 6]]


In [75]:
C= np.array([1,2,3,4,5])
D= C.T
E = C.reshape(1,5)
F = E.T
print(F)

[[1]
 [2]
 [3]
 [4]
 [5]]
